// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package ictBridge

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindTransactionsByAddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTransactionsByAddressRequest) Reset()         { *m = FindTransactionsByAddressRequest{} }
func (m *FindTransactionsByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*FindTransactionsByAddressRequest) ProtoMessage()    {}
func (*FindTransactionsByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *FindTransactionsByAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTransactionsByAddressRequest.Unmarshal(m, b)
}
func (m *FindTransactionsByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTransactionsByAddressRequest.Marshal(b, m, deterministic)
}
func (m *FindTransactionsByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTransactionsByAddressRequest.Merge(m, src)
}
func (m *FindTransactionsByAddressRequest) XXX_Size() int {
	return xxx_messageInfo_FindTransactionsByAddressRequest.Size(m)
}
func (m *FindTransactionsByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTransactionsByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindTransactionsByAddressRequest proto.InternalMessageInfo

func (m *FindTransactionsByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type FindTransactionsByTagRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTransactionsByTagRequest) Reset()         { *m = FindTransactionsByTagRequest{} }
func (m *FindTransactionsByTagRequest) String() string { return proto.CompactTextString(m) }
func (*FindTransactionsByTagRequest) ProtoMessage()    {}
func (*FindTransactionsByTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{1}
}

func (m *FindTransactionsByTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTransactionsByTagRequest.Unmarshal(m, b)
}
func (m *FindTransactionsByTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTransactionsByTagRequest.Marshal(b, m, deterministic)
}
func (m *FindTransactionsByTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTransactionsByTagRequest.Merge(m, src)
}
func (m *FindTransactionsByTagRequest) XXX_Size() int {
	return xxx_messageInfo_FindTransactionsByTagRequest.Size(m)
}
func (m *FindTransactionsByTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTransactionsByTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindTransactionsByTagRequest proto.InternalMessageInfo

func (m *FindTransactionsByTagRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type FindTransactionByHashRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTransactionByHashRequest) Reset()         { *m = FindTransactionByHashRequest{} }
func (m *FindTransactionByHashRequest) String() string { return proto.CompactTextString(m) }
func (*FindTransactionByHashRequest) ProtoMessage()    {}
func (*FindTransactionByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{2}
}

func (m *FindTransactionByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTransactionByHashRequest.Unmarshal(m, b)
}
func (m *FindTransactionByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTransactionByHashRequest.Marshal(b, m, deterministic)
}
func (m *FindTransactionByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTransactionByHashRequest.Merge(m, src)
}
func (m *FindTransactionByHashRequest) XXX_Size() int {
	return xxx_messageInfo_FindTransactionByHashRequest.Size(m)
}
func (m *FindTransactionByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTransactionByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindTransactionByHashRequest proto.InternalMessageInfo

func (m *FindTransactionByHashRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type SubmitTransactionBuilderRequest struct {
	TransactionBuilder   *TransactionBuilder `protobuf:"bytes,1,opt,name=transactionBuilder,proto3" json:"transactionBuilder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SubmitTransactionBuilderRequest) Reset()         { *m = SubmitTransactionBuilderRequest{} }
func (m *SubmitTransactionBuilderRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionBuilderRequest) ProtoMessage()    {}
func (*SubmitTransactionBuilderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{3}
}

func (m *SubmitTransactionBuilderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionBuilderRequest.Unmarshal(m, b)
}
func (m *SubmitTransactionBuilderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionBuilderRequest.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionBuilderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionBuilderRequest.Merge(m, src)
}
func (m *SubmitTransactionBuilderRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionBuilderRequest.Size(m)
}
func (m *SubmitTransactionBuilderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionBuilderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionBuilderRequest proto.InternalMessageInfo

func (m *SubmitTransactionBuilderRequest) GetTransactionBuilder() *TransactionBuilder {
	if m != nil {
		return m.TransactionBuilder
	}
	return nil
}

type SubmitTransactionBytesRequest struct {
	TransactionBytes     []byte   `protobuf:"bytes,1,opt,name=transactionBytes,proto3" json:"transactionBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitTransactionBytesRequest) Reset()         { *m = SubmitTransactionBytesRequest{} }
func (m *SubmitTransactionBytesRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionBytesRequest) ProtoMessage()    {}
func (*SubmitTransactionBytesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{4}
}

func (m *SubmitTransactionBytesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionBytesRequest.Unmarshal(m, b)
}
func (m *SubmitTransactionBytesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionBytesRequest.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionBytesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionBytesRequest.Merge(m, src)
}
func (m *SubmitTransactionBytesRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionBytesRequest.Size(m)
}
func (m *SubmitTransactionBytesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionBytesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionBytesRequest proto.InternalMessageInfo

func (m *SubmitTransactionBytesRequest) GetTransactionBytes() []byte {
	if m != nil {
		return m.TransactionBytes
	}
	return nil
}

type AddEffectListenerRequest struct {
	Environment          string   `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEffectListenerRequest) Reset()         { *m = AddEffectListenerRequest{} }
func (m *AddEffectListenerRequest) String() string { return proto.CompactTextString(m) }
func (*AddEffectListenerRequest) ProtoMessage()    {}
func (*AddEffectListenerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{5}
}

func (m *AddEffectListenerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEffectListenerRequest.Unmarshal(m, b)
}
func (m *AddEffectListenerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEffectListenerRequest.Marshal(b, m, deterministic)
}
func (m *AddEffectListenerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEffectListenerRequest.Merge(m, src)
}
func (m *AddEffectListenerRequest) XXX_Size() int {
	return xxx_messageInfo_AddEffectListenerRequest.Size(m)
}
func (m *AddEffectListenerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEffectListenerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEffectListenerRequest proto.InternalMessageInfo

func (m *AddEffectListenerRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

type RemoveEffectListenerRequest struct {
	Environment          string   `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEffectListenerRequest) Reset()         { *m = RemoveEffectListenerRequest{} }
func (m *RemoveEffectListenerRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveEffectListenerRequest) ProtoMessage()    {}
func (*RemoveEffectListenerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{6}
}

func (m *RemoveEffectListenerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEffectListenerRequest.Unmarshal(m, b)
}
func (m *RemoveEffectListenerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEffectListenerRequest.Marshal(b, m, deterministic)
}
func (m *RemoveEffectListenerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEffectListenerRequest.Merge(m, src)
}
func (m *RemoveEffectListenerRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveEffectListenerRequest.Size(m)
}
func (m *RemoveEffectListenerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEffectListenerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEffectListenerRequest proto.InternalMessageInfo

func (m *RemoveEffectListenerRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

type SubmitEffectRequest struct {
	Environment          string   `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	Effect               string   `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitEffectRequest) Reset()         { *m = SubmitEffectRequest{} }
func (m *SubmitEffectRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitEffectRequest) ProtoMessage()    {}
func (*SubmitEffectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{7}
}

func (m *SubmitEffectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitEffectRequest.Unmarshal(m, b)
}
func (m *SubmitEffectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitEffectRequest.Marshal(b, m, deterministic)
}
func (m *SubmitEffectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitEffectRequest.Merge(m, src)
}
func (m *SubmitEffectRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitEffectRequest.Size(m)
}
func (m *SubmitEffectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitEffectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitEffectRequest proto.InternalMessageInfo

func (m *SubmitEffectRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *SubmitEffectRequest) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

type PollEffectRequest struct {
	Environment          string   `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollEffectRequest) Reset()         { *m = PollEffectRequest{} }
func (m *PollEffectRequest) String() string { return proto.CompactTextString(m) }
func (*PollEffectRequest) ProtoMessage()    {}
func (*PollEffectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{8}
}

func (m *PollEffectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollEffectRequest.Unmarshal(m, b)
}
func (m *PollEffectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollEffectRequest.Marshal(b, m, deterministic)
}
func (m *PollEffectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollEffectRequest.Merge(m, src)
}
func (m *PollEffectRequest) XXX_Size() int {
	return xxx_messageInfo_PollEffectRequest.Size(m)
}
func (m *PollEffectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PollEffectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PollEffectRequest proto.InternalMessageInfo

func (m *PollEffectRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

type TakeEffectRequest struct {
	Environment          string   `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TakeEffectRequest) Reset()         { *m = TakeEffectRequest{} }
func (m *TakeEffectRequest) String() string { return proto.CompactTextString(m) }
func (*TakeEffectRequest) ProtoMessage()    {}
func (*TakeEffectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{9}
}

func (m *TakeEffectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeEffectRequest.Unmarshal(m, b)
}
func (m *TakeEffectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeEffectRequest.Marshal(b, m, deterministic)
}
func (m *TakeEffectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeEffectRequest.Merge(m, src)
}
func (m *TakeEffectRequest) XXX_Size() int {
	return xxx_messageInfo_TakeEffectRequest.Size(m)
}
func (m *TakeEffectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeEffectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TakeEffectRequest proto.InternalMessageInfo

func (m *TakeEffectRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func init() {
	proto.RegisterType((*FindTransactionsByAddressRequest)(nil), "FindTransactionsByAddressRequest")
	proto.RegisterType((*FindTransactionsByTagRequest)(nil), "FindTransactionsByTagRequest")
	proto.RegisterType((*FindTransactionByHashRequest)(nil), "FindTransactionByHashRequest")
	proto.RegisterType((*SubmitTransactionBuilderRequest)(nil), "SubmitTransactionBuilderRequest")
	proto.RegisterType((*SubmitTransactionBytesRequest)(nil), "SubmitTransactionBytesRequest")
	proto.RegisterType((*AddEffectListenerRequest)(nil), "AddEffectListenerRequest")
	proto.RegisterType((*RemoveEffectListenerRequest)(nil), "RemoveEffectListenerRequest")
	proto.RegisterType((*SubmitEffectRequest)(nil), "SubmitEffectRequest")
	proto.RegisterType((*PollEffectRequest)(nil), "PollEffectRequest")
	proto.RegisterType((*TakeEffectRequest)(nil), "TakeEffectRequest")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd2, 0xdf, 0x4b, 0xc3, 0x30,
	0x10, 0x07, 0x70, 0xa6, 0x32, 0xf1, 0xaa, 0x30, 0x3b, 0x90, 0xe2, 0x0f, 0x2c, 0x79, 0x12, 0x1f,
	0x86, 0x4c, 0x7c, 0x1b, 0xc8, 0x26, 0x8a, 0xa0, 0xa0, 0xd4, 0xfe, 0x03, 0xd9, 0x72, 0x5d, 0x83,
	0x6d, 0xa2, 0xc9, 0x75, 0xd0, 0xff, 0x5e, 0x96, 0xb6, 0x3a, 0xec, 0x1e, 0x9c, 0x6f, 0xb9, 0xbb,
	0x7e, 0xbe, 0xe9, 0x95, 0xc2, 0x81, 0xc1, 0xcf, 0x02, 0x2d, 0x0d, 0x3e, 0x8c, 0x26, 0x7d, 0xec,
	0xe5, 0x5a, 0x60, 0x56, 0x15, 0x6c, 0x04, 0xe1, 0x83, 0x54, 0x22, 0x36, 0x5c, 0x59, 0x3e, 0x23,
	0xa9, 0x95, 0x9d, 0x94, 0x63, 0x21, 0x0c, 0x5a, 0x1b, 0x55, 0xcc, 0x0f, 0x60, 0x97, 0x57, 0x9d,
	0xa0, 0x13, 0x76, 0x2e, 0xf6, 0xa2, 0xa6, 0x64, 0x57, 0x70, 0xda, 0xd6, 0x31, 0x9f, 0x37, 0xb2,
	0x07, 0xdb, 0xc4, 0xe7, 0xb5, 0x5a, 0x1e, 0xd9, 0xb0, 0x25, 0x26, 0xe5, 0x23, 0xb7, 0x69, 0x23,
	0x7c, 0xd8, 0x49, 0xb9, 0x4d, 0x6b, 0xe2, 0xce, 0x2c, 0x81, 0xf3, 0xb7, 0x62, 0x9a, 0x4b, 0x5a,
	0x55, 0x85, 0xcc, 0x04, 0x9a, 0x86, 0xdd, 0x81, 0x4f, 0xad, 0xa1, 0x0b, 0xf1, 0x86, 0xfd, 0xc1,
	0x1a, 0xb7, 0xe6, 0x71, 0xf6, 0x04, 0x67, 0xed, 0x7b, 0x4a, 0xc2, 0xef, 0x0f, 0x71, 0x09, 0x3d,
	0xfa, 0x35, 0x72, 0x77, 0xec, 0x47, 0xad, 0x3e, 0x1b, 0x41, 0x30, 0x16, 0xe2, 0x3e, 0x49, 0x70,
	0x46, 0xcf, 0xd2, 0x12, 0xaa, 0x9f, 0xb7, 0x0d, 0xc1, 0x43, 0xb5, 0x90, 0x46, 0xab, 0x1c, 0x15,
	0xd5, 0xbb, 0xae, 0xb6, 0xd8, 0x2d, 0x9c, 0x44, 0x98, 0xeb, 0x05, 0xfe, 0x37, 0xe0, 0x05, 0xfa,
	0xd5, 0x2e, 0x55, 0xc0, 0x9f, 0xa1, 0x7f, 0x04, 0x5d, 0x74, 0x24, 0xd8, 0x72, 0xc3, 0xba, 0x62,
	0x37, 0x70, 0xf8, 0xaa, 0xb3, 0x6c, 0xc3, 0xb8, 0x25, 0x8b, 0xf9, 0x3b, 0x6e, 0xc8, 0xa6, 0x5d,
	0xf7, 0x77, 0x5e, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x18, 0x6d, 0x7c, 0xbb, 0x02, 0x00,
	0x00,
}
